feature: Add option `umdExportName`, which enables to specify a UMD export name and create a pure UMD self-contained bundle to avoid TS error TS1471 in TSv4.7~TSv5.7 when `moduleResolution: "NodeNext"` is used.